First attempt to add subdir to local. Issue #1: this variable is abused remotely.

diff --git a/btrfs-subvolume-backup b/btrfs-subvolume-backup
--- a/btrfs-subvolume-backup
+++ b/btrfs-subvolume-backup
@@ -34,6 +34,7 @@ Options:
     --keep num:      Keep the last snapshots for local backups (5 by default)
     --dest hostname: If present, ssh to that machine to make the copy.
     --diff:	     show an approximate diff between the snapshots
+    --local:         the directory containing local snapshots
 
 This will snapshot volume_name in a btrfs pool, and send the diff
 between it and the previous snapshot (volume_name.last) to another btrfs
@@ -77,11 +78,12 @@ trap 'die "Error line $LINENO with status $?"' ERR
 init=""
 # Keep the last 5 snapshots by default
 keep=5
-TEMP=$(getopt --longoptions help,usage,init,keep:,dest:,prefix:,diff -o h,k:,d:,p: -- "$@") || usage
+TEMP=$(getopt --longoptions help,usage,init,keep:,dest:,prefix:,local:,diff -o h,k:,d:,p: -- "$@") || usage
 dest=localhost
 ssh=""
 pf=""
 diff=""
+local="."
 
 # getopt quotes arguments with ' We use eval to get rid of that
 eval set -- $TEMP
@@ -98,6 +100,12 @@ do
 	    shift
 	    pf=_$1
 	    lock="$lock.$pf"
+	    shift
+	    ;;
+
+	--local)
+	    shift
+	    local=$1
 	    shift
 	    ;;
 
@@ -151,13 +159,17 @@ if ! shlock -p $$ -f $lock; then
     exit
 fi
 
-if [[ -z "$init" ]]; then
-    test -e "${vol}${pf}_last" \
-	|| die "Cannot sync $vol, ${vol}${pf}_last missing. Try --init?"
-    src_snap="$(readlink -e ${vol}${pf}_last)"
+if [[ ! -d "$local" ]]; then
+    mkdir "$local"
 fi
-src_newsnap="${vol}${pf}_ro.$DATE"
-src_newsnaprw="${vol}${pf}_rw.$DATE"
+
+if [[ -z "$init" ]]; then
+    test -e "${local}/${vol}${pf}_last" \
+	|| die "Cannot sync $vol, ${local}/${vol}${pf}_last missing. Try --init?"
+    src_snap="$(readlink -e ${local}/${vol}${pf}_last)"
+fi
+src_newsnap="${local}/${vol}${pf}_ro.$DATE"
+src_newsnaprw="${local}/${vol}${pf}_rw.$DATE"
 
 $ssh test -d "$dest_pool/" || die "ABORT: $dest_pool not a directory (on $dest)"
 
@@ -186,18 +198,18 @@ btrfs subvolume snapshot "$src_newsnap" "$src_newsnaprw"
 $ssh btrfs subvolume snapshot "$dest_pool/$src_newsnap" "$dest_pool/$src_newsnaprw"
 
 # Keep track of the last snapshot to send a diff against.
-ln -snf $src_newsnap ${vol}${pf}_last
+ln -snf $src_newsnap ${local}/${vol}${pf}_last
 # The rw version can be used for mounting with subvol=vol_last_rw
-ln -snf $src_newsnaprw ${vol}${pf}_last_rw
+ln -snf $src_newsnaprw ${local}/${vol}${pf}_last_rw
 $ssh ln -snf $src_newsnaprw $dest_pool/${vol}${pf}_last_rw
 
 # How many snapshots to keep on the source btrfs pool (both read
 # only and read-write).
-ls -rd ${vol}${pf}_ro* | tail -n +$(( $keep + 1 ))| while read snap
+ls -rd ${local}/${vol}${pf}_ro* | tail -n +$(( $keep + 1 ))| while read snap
 do
     btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
 done
-ls -rd ${vol}${pf}_rw* | tail -n +$(( $keep + 1 ))| while read snap
+ls -rd ${local}/${vol}${pf}_rw* | tail -n +$(( $keep + 1 ))| while read snap
 do
     btrfs subvolume delete "$snap" | grep -v 'Transaction commit:'
 done
